name: share_delivery
description: share delivery

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  flutter_native_splash: ^2.1.5
  numberpicker: ^2.1.1
  webview_flutter: ^3.0.2
  kakaomap_webview: ^0.5.1
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.3
  location: ^4.3.0
  http: ^0.13.4
  loader_overlay: ^2.0.6
  shared_preferences: ^2.0.13
  freezed_annotation: ^2.0.1
  geolocator: ^8.2.1
  share_plus: ^4.0.4
  flutter_persistent_keyboard_height: ^1.0.5
  flutter_spinkit: ^5.1.0
  images_picker: ^1.2.11

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.15
  flutter_local_notifications: ^9.4.1
  timeago: ^3.2.2
  mockito: ^5.2.0
  dio: ^4.0.6
  json_annotation: ^4.5.0
  retrofit: ^3.0.1
  logger: ^1.1.0
  pull_to_refresh: ^2.0.0
  percent_indicator: ^3.4.0
  url_launcher: ^6.1.2
  sms_autofill: ^2.2.0
  clipboard: ^0.1.3
  safe_clipboard: ^0.0.2
  link_text: ^0.2.0
  shimmer: ^2.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  badges: ^2.0.2
  socket_io_client: ^1.0.2
  keyboard_attachable: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash/delivery_icon.png
